services:

  postgres:
    restart: unless-stopped
    cpus: "0.25"
    mem_limit: 384m
    mem_reservation: 192m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  odoo:
    restart: unless-stopped
    cpus: "0.70"
    mem_limit: 900m
    mem_reservation: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  react:
    restart: unless-stopped
    cpus: "0.05"
    mem_limit: 96m
    mem_reservation: 32m
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  nginx:
    restart: unless-stopped
    cpus: "0.10"
    mem_limit: 96m
    mem_reservation: 32m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  company-backend:
    restart: unless-stopped
    cpus: "0.20"
    mem_limit: 256m
    mem_reservation: 96m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
